### PR TITLE
Update README.md

### LINKED ISSUE #250: Testnet faucet link not working
The testnet faucet link mentioned in [Readme](https://github.com/thunderbiscuit/padawan-wallet#where-can-i-get-testnet-coins) is not working https://testnet-faucet.mempool.co/. Do we have an alternative to this faucet or a new link? If there is one we should update it.

### PR DESCRIPTION
**Pull request by Prakhar-Agarwal-byte**
Update links to testnet faucets. Fixes #250

### CODE REVIEW

**Review by thunderbiscuit — APPROVED** [review]
ACK 20dd13c59e1d1dd08d6c4f962b662b8d5e0aa93f. Thanks!

**Comment by thunderbiscuit** [comment]
The CI is failing but that's because of changes made in the 0.10.0 release. Haven't looked into it but let's open an issue to keep track of it and fix it.

**Comment by thunderbiscuit** [comment]
Actually would you mind amending the commit message?

In this case the tag applied would be `Docs`. So the message would be `Docs: Update README.md`

**Comment by Prakhar-Agarwal-byte** [comment]
@thunderbiscuit I have ammended the commit message.

**Comment by thunderbiscuit** [comment]
Almost there! The tag is actually `Docs`, not `Doc` 😆. It's not a big thing but because those tags are meant for tools that would parse your commit history, typos will prevent the machine from properly finding them.

Also, would you mind squashing all of those into 1 commit? I don't want to assume your level of comfort with git so let me know if you'd like some pointers. Essentially I'm looking for 1, clean commit. You might need to do an interactive rebase to clean this up. [This is the best article on interactive rebase](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history) I think.

**Comment by thunderbiscuit** [comment]
Perfect. Ready for merge.

**Comment by thunderbiscuit** [comment]
The GitHub UI is not picking up the fact that I merged this commit under a different hash. Closing now because it's been merged!

**Pull request closed without merging**
