### PR TITLE
Fix: reset done tutorials requires app restart #88

### LINKED ISSUE #88: Reset done tutorials requires app restart

### PR DESCRIPTION
**Pull request by darkvoid32**
Fixes #88 by Added a flag to **Repository.kt** so that when user resets their tutorials **TutorialsHome.kt** fragment will check for and update UI if necessary. 
I think this is the simplest fix unless its easier to redraw the **TutorialsHome.kt** fragment.

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
Tested ACK. To me the whole "done" tutorials workflow and code looks just so wrong at this point 🤣, I do hope to find a better solution once the wallet gets ported to Compose. 

But for now this is a good/hacky enough way to do it!

Thanks 👍

**Comment by thunderbiscuit** [comment]
Just one thing: would you mind squashing those two commits into one?

**Comment by darkvoid32** [comment]
Ok, I'll get back to you once I've done that! Still not very fluent in git workflows.

**Comment by thunderbiscuit** [comment]
Yeah I think Compose should solve that nicely. For the workflow I think what you want to do is an interactive rebase (look it up). Something like `git rebase --interactive HEAD~2 will allow you to squash those two commits into one.

https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history

**Comment by darkvoid32** [comment]
Okay, I think I got it 👍

**Pull request merged**
