### PR TITLE
Resolved the issue by adding padding

### PR DESCRIPTION
**Pull request by ConnectBhawna**
Resolved the issue number : #243
Added some padding between the Getting Started and 1 of 3 Done

### CODE REVIEW

**Review by thunderbiscuit — CHANGES_REQUESTED** [review]
Awesome! Can you post screenshots of what the fix changes on smaller screens? Also I'm wondering if that's required on the second carousel item (Section 2: Transactions). Can you let me know what the screen look like for the other two?

Also I think you introduced an unwanted change to the `ChapterScreen`.

For the commit message you're not specifying _what_ issue you're fixing (`resolved the issue by adding padding`). Make sure you follow the Padawan standard of using conventional commits and capitalizing the first letter of the message. Something like:
```txt
UI: Fix padding issue for small screens in carousel
```

**Comment by ConnectBhawna** [comment]
Okk sir will do this by today :)

**Comment by thunderbiscuit** [comment]
@ConnectBhawna are you still working on this?

**Comment by ConnectBhawna** [comment]
Yups sir, sorry for the delayed response

**Comment by thunderbiscuit** [comment]
@ConnectBhawna let me know if you'd like me to fix this up for you and we can merge.

**Comment by ConnectBhawna** [comment]
I will make the new PR for the same :)

**Pull request closed without merging**
