### PR TITLE
Feat: Merged WalletBuild and WalletBroadcast by adding MaterialAlertDialogBox

### PR DESCRIPTION
**Pull request by sunidhi64**
Added a MaterialAlertDialogBox which will confirm from user whether to broadcast transaction or not in WalletBuild.

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
Thanks for the PR! I won't be able to take a look until tomorrow at the earliest, but I'll give feedback for sure!

**Comment by thunderbiscuit** [comment]
I think you opened the PR on an older version of dev. I see that your first commit is `Feat: Added a scrollView in recover wallet`, but that commit has already been merged.

Do you mind opening a new PR on the latest dev? The way you would do it is the following:
1. In your fork of padawan-wallet, pull the latest changes to `dev` using something like `git pull upstream dev`. This should make sure you have all the commits from the upstream (mine) `dev` branch.
2. Create a branch off of that `dev` branch called whatever you want (something descriptive, like `feat/broadcast-dialog`)
3. From there you can apply the changes that are only related to this PR (your second commit).
4. Open the PR, and I think we're good to go!

**Comment by thunderbiscuit** [comment]
Also, I already I have branches called `feat/...` and somehow I think your branch being called just `feat` (which is a subset of the string of mine) is creating problems... not sure why, but I can't pull your PR locally to test! Sorry. I think you'll have to use branch names that are not subsets of mine. Just add a word after your `feat` to describe it and I'll be good to pull!

**Comment by sunidhi64** [comment]
> I think you opened the PR on an older version of dev. I see that your first commit is `Feat: Added a scrollView in recover wallet`, but that commit has already been merged.
> 
> Do you mind opening a new PR on the latest dev? The way you would do it is the following:
> 
> 1. In your fork of padawan-wallet, pull the latest changes to `dev` using something like `git pull upstream dev`. This should make sure you have all the commits from the upstream (mine) `dev` branch.
> 2. Create a branch off of that `dev` branch called whatever you want (something descriptive, like `feat/broadcast-dialog`)
> 3. From there you can apply the changes that are only related to this PR (your second commit).
> 4. Open the PR, and I think we're good to go!

Yes I on it.

**Pull request closed without merging**
