### PR TITLE
removed hard-coded strings from IntroFragment.kt

### LINKED ISSUE #155: Remove hard-coded strings in IntroFragment
They should be migrated to `strings.xml`.

### PR DESCRIPTION
**Pull request by dhruv-1001**
Fixes #155 

Strings migrated to `strings.xml` as:
```
<string name="intro_dialog_message">...</string>
<string name="intro_dialog_title">...</string>
<string name="intro_dialog_positive">...</string>
<string name="intro_dialog_negative">...</string>
```

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
Awesome! Thanks a bunch. 

Just a quick fix: your commit message should follow the convention I'm using, which is:

1. Start with a tag, capitalized (in your case `Refactor:`)
2. Present-tense statement answering the question: "What does this commit do?", also capitalized

So for this one it would look something like this: `Refactor: Move hard-coded strings from IntroFragment to strings.xml`

Otherwise it's ready to merge!

**Comment by thunderbiscuit** [comment]
If you need help with fixing the message and force pushing to the PR let me know!

**Comment by dhruv-1001** [comment]
Thanks for the suggestion, I hope it's alright now.

**Comment by thunderbiscuit** [comment]
Yep thanks for the contribution, and welcome to Padawan!

**Pull request merged**
