### PR TITLE
Fix: Sync wallet on startup and stop crashing when changing tabs during sync

### LINKED ISSUE #127: Sync wallet on startup

### LINKED ISSUE #139: App crashes if user changes fragment while sync is happening
This is because the coroutine launches the snackbar with the view given in `WalletHome`, and if the use is in, say, the receive fragment, it cannot find this view in which to launch the snackbar.

Error:
```sh
2021-08-26 18:52:37.435 20721-20905/com.goldenraven.padawanwallet.debug E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-4
    Process: com.goldenraven.padawanwallet.debug, PID: 20721
    java.lang.IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
        at com.google.android.material.snackbar.Snackbar.makeInternal(Snackbar.java:198)
        at com.google.android.material.snackbar.Snackbar.make(Snackbar.java:157)
        at com.goldenraven.padawanwallet.utils.SnackbarsKt.fireSnackbar(Snackbars.kt:31)
        at com.goldenraven.padawanwallet.utils.SnackbarsKt.fireSnackbar$default(Snackbars.kt:15)
        at com.goldenraven.padawanwallet.wallet.wallet.WalletHome$onViewCreated$2$1$1.invokeSuspend(WalletHome.kt:95)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7615)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

### PR DESCRIPTION
**Pull request by darkvoid32**
Fixes #127 by calling a coroutine in the `onCreateView` so the view only calls it once on startup.
Fixes #139 by calling the snackbar using the `rootView` instead of the child view, so switching fragments will not cause it to crash the app.

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
I think this is good to go. Small little thing: usually I'm not a big fan of the not-null assertion operator. Are we sure this rootView can never be null?

**Comment by thunderbiscuit** [comment]
I think this is good to go. Small little thing: usually I'm not a big fan of the not-null assertion operator. Are we sure this rootView can never be null?

**Comment by darkvoid32** [comment]
I'll look into it and get back to you

**Comment by darkvoid32** [comment]
Ok, I've changed intializing `rootView` from `container?.root` to simply calling `binding.root`, which I should have done from the beginning.

**Comment by thunderbiscuit** [comment]
Good stuff.

**Pull request merged**
