### PR TITLE
[WIP] Added Sort transaction feature.

### PR DESCRIPTION
**Pull request by prateek-singh-3212**
Issue: #231 

Currently this Feature is under development. So, I am creating this PR as draft. I will update the status of this PR here.
Implementing sort transaction based on:
1. Amount spend
2. Time of Transaction

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
@prateek-singh-3212 are you still working on this? Let me know if it's ready for review or if you'd rather I close it if you don't have time to finish it. Thanks!

**Comment by prateek-singh-3212** [comment]
I am working on it. Sure, I will let you know.

**Comment by thunderbiscuit** [comment]
I will close this if it hasn't seen any progress by the end of July. No hard feelings at all if you're working on other things! I'm just trying to clean up the repo at the moment and will update/close issues and PRs over the next few weeks.

**Comment by thunderbiscuit** [comment]
Closing now. Feel free to reopen if you end up working on this again!

**Pull request closed without merging**
