### PR TITLE
Show copied to clipboard snackbar

### LINKED ISSUE #241: Add a toast on copying Padawan address
We can add a toast saying address copied when the user clicks on Padawan address in send coins back to us section. This will give feedback to user that the address was copied successfully. 

**Screenshot:**
WhatsApp Image 2023-03-01 at 1 46 04 AM

### PR DESCRIPTION
**Pull request by Prakhar-Agarwal-byte**
Fixes #241, #201 

**Screenshot:**
WhatsApp Image 2023-03-01 at 3 06 07 AM

### CODE REVIEW

**Comment by darkvoid32** [comment]
Hi Prakhar thanks for opening up the PR for this issue! 
With regards to issue #201 , does this PR also fix the unwanted toast being fired in other API versions? Just wanted to check since we are not sure why the toast was being fired in the first place.

**Comment by Prakhar-Agarwal-byte** [comment]
I tested it on API 30 didn't get the toast anymore.

**Review by thunderbiscuit — APPROVED** [review]
ACK 875f81cddd9b0bf07238c7546eb243b9ec672df0.

**Comment by thunderbiscuit** [comment]
@Prakhar-Agarwal-byte please rebase to pick up the latest changes on master and I'll merge this one next.

**Comment by Prakhar-Agarwal-byte** [comment]
Rebased on master

**Pull request merged**
