### PR TITLE
Docs: Add CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by ConnectBhawna**
I have added a Code of conduct along with Contributing guidelines to the project. In my Contributing guideline, I have not provided a link for the IHR Code of conduct, in case this gets merged I would add the link else the link would redirect to my repo. Let me know what you think about the rules and approach I have provided. @thunderbiscuit sir incase you need some changes let me know I would make and send the PR again.

Solved issue https://github.com/thunderbiscuit/padawan-wallet/issues/245

### CODE REVIEW

**Review by thunderbiscuit — CHANGES_REQUESTED** [review]
Hi! As per #244, let's remove the code of conduct file from this PR.

**Comment by thunderbiscuit** [comment]
Thank you! Now you have 2 commits that simply need to be squashed and this one is ready to go.

**Comment by ConnectBhawna** [comment]
Okk sir, I will do this by today :)

**Comment by thunderbiscuit** [comment]
@ConnectBhawna let me know if you're still interested in getting this merged. I think it's almost there...

**Comment by ConnectBhawna** [comment]
Yes sir, Let me know what i need to change now

**Review by thunderbiscuit — APPROVED** [review]
Oh this was actually already squashed! Sorry. Ready to go.

**Pull request merged**
